name: Auto-register

on:
  push:
    branches:
      - main
    paths:
      - 'Project.toml'
  workflow_dispatch: null

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  autoregister:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.11']
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - uses: actions/cache@v1
        env:
          cache-name: cache-artifacts
        with:
          path: ~/.julia/artifacts
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/Project.toml') }}
          restore-keys: |
            ${{ runner.os }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-test-
            ${{ runner.os }}-
      - run: |
          git config --global user.email "isamborg@cosroe.com"
          git config --global user.name "Isamborg"
          julia -e '
          import Pkg
          Pkg.add(url="https://github.com/GunnarFarneback/LocalRegistry.jl")
          using LocalRegistry
          Pkg.Registry.add(Pkg.RegistrySpec(url="https://github.com/astro-group-bristol/AstroRegistry/"))
          try
            register(pwd(), registry="AstroRegistry", push=false)
          catch err
            @warn err
          end
          try
            register(joinpath(pwd(), "lib", "XSPECModels"), registry="AstroRegistry", push=false)
          catch err
            @warn err
          end
          '
      - name: Create new branch
        run: |
          cd ~/.julia/registries/AstroRegistry
          git checkout -b "bot/spectralfitting"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.SECRET_PR_TOKEN }}
          repository: "astro-group-bristol/AstroRegistry"
          directory: "/home/runner/.julia/registries/AstroRegistry"
          branch: "bot/spectralfitting"
      - name: Create pull request
        run: |
          cd ~/.julia/registries/AstroRegistry
          gh pr create -B main \
            --title "New Version: SpectralFitting" \
            --body "Automated pull request." \
            -H "bot/spectralfitting"
        env:
            GITHUB_TOKEN: ${{ secrets.SECRET_PR_TOKEN }}
